[package]
name = "wsv"
version = "0.1.3"
authors = ["honestlysamuk"]
edition = "2021"
description = "A Rust implementation of the Whitespace-separated values, as defined by Stenway. Follow the release notes on https://honestlysam.uk"
license = "MIT"
homepage = "https://dev.stenway.com/WSV/"
documentation = "https://dev.stenway.com/WSV/"
repository = "https://github.com/honestlysamuk/wsv"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-bom = "2"
